---
name: CI

on:
  push:
  pull_request:

env:
  NIX_CONFIG: experimental-features = nix-command flakes

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-nix
      - name: Check formatting
        run: |
          nix fmt
          git diff --exit-code

  lint-nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-nix
      - name: Lint Nix
        run: nix run .#lint_nix

  lint-bash:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-nix
      - name: Lint shell fragments
        run: nix run .#lint_bash

  lint-editorconfig:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-nix
      - name: Lint files with editorconfig-checker
        run: nix run .#lint_editor

  flake-check:
    needs:
      - format
      - lint-nix
      - lint-bash
      - lint-editorconfig
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: ./.github/actions/setup-nix
      - name: Run flake checks
        run: nix flake check
